// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lgemepjwfacalnrfkrex.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxnZW1lcGp3ZmFjYWxucmZrcmV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQyNTQxNzMsImV4cCI6MjA0OTgzMDE3M30.VQSJ3npu0ryMqLLikpehv6FGiVVc9qRNNyZy29xj9go";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);